=== juan022/asix22/m04/uf1/a2/act8/jpsanchez_a2_act8_ex3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="arqueologia">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="jaciment" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="localitzacio">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nom_pais" type="Limitarcar" />
                                        <xs:element name="nom_ciutat" type="Limitarcar" />
                                        <xs:element name="coordenades">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="longitud" type="xs:decimal" />
                                                    <xs:element name="latitud" type="xs:decimal" />
                                                    <xs:element name="orientacio">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="N" />
                                                                <xs:enumeration value="S" />
                                                                <xs:enumeration value="E" />
                                                                <xs:enumeration value="O" />
                                                                <xs:enumeration value="NE" />
                                                                <xs:enumeration value="SE" />
                                                                <xs:enumeration value="SO" />
                                                                <xs:enumeration value="NO" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="troballes">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="peÃ§a" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:choice>
                                                        <xs:element name="descripcio" type="Limitarcar" />
                                                        <xs:element name="dibuix" />
                                                    </xs:choice>
                                                    <xs:element name="data" type="xs:date" />
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:ID" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="epoca" type="Limitarcar"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="Limitarcar">
        <xs:restriction base="xs:string">
            <xs:maxLength value="20" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== juan022/asix22/m04/uf1/a2/act8/jpsanchez_a2_act8_ex3.xml
<?xml version="1.0" encoding="UTF-8"?>
<arqueologia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jpsanchez_a2_act8_ex3.xsd">
    <jaciment epoca="pre-romanic">
        <localitzacio>
            <nom_pais>Italia</nom_pais>
            <nom_ciutat>Roma</nom_ciutat>
            <coordenades>
                <longitud>275.3</longitud>
                <latitud>145.6</latitud>
                <orientacio>NE</orientacio>
            </coordenades>
        </localitzacio>
        <troballes>
            <peça id="_12" >
                <descripcio>Trident coure</descripcio>
                <data>1990-08-25</data>
            </peça>
        </troballes>
    </jaciment>
</arqueologia>
