=== juan022/asix22/m04/uf1/a2/act8/personal.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="personal">
        <xs:complexType>
            <xs:all>
                <xs:element name="datos-generales" type="tipoDatosGenerales" minOccurs="1" maxOccurs="1" />
                <xs:element name="datos-departamentos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="departamento" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="jefe" type="tipoJefe" minOccurs="1" maxOccurs="1" />
                                        <xs:element name="empleado" type="tipoEmpleado" minOccurs="0" maxOccurs="3" />
                                    </xs:sequence>
                                    <xs:attributeGroup ref="AtributosDepartamento" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
            <xs:attributeGroup ref="AtributosPersonal" />
        </xs:complexType>
    </xs:element>

    <xs:complexType name="tipoDatosGenerales">
        <xs:sequence>
            <xs:element name="nombre-empresa" type="tipoTexto" minOccurs="1" maxOccurs="1" />
            <xs:element name="numero-trabajadores" type="xs:positiveInteger" minOccurs="1" maxOccurs="1" />
            <xs:element name="sector">
                <xs:complexType>
                    <xs:sequence>
                        <xs:group ref="sectores" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoJefe">
        <xs:complexContent>
            <xs:extension base="tipoEmpleado">
                <xs:sequence>
                    <xs:element name="clave">
                        <xs:complexType>
                            <xs:simpleContent>
                                <xs:extension base="tipoClave">
                                    <xs:attribute name="usuario" default="invitado" use="optional" >
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:maxLength value="8" />
                                                <xs:minLength value="6" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:extension>
                            </xs:simpleContent>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="tipoEmpleado">
        <xs:sequence>
            <xs:element name="nombre-y-apellidos" type="tipoTexto" minOccurs="1" maxOccurs="1" />
            <xs:element name="baja" minOccurs="0" maxOccurs="1" />
            <xs:element name="salario">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal" >
                        <xs:minInclusive value="1000" />
                        <xs:maxInclusive value="9999" />
                        <xs:totalDigits value="6" />
                        <xs:fractionDigits value="2" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:group name="sectores">
        <xs:choice>
            <xs:element name="educacion" />
            <xs:element name="finanza" />
            <xs:element name="tecnologia" />
        </xs:choice>
    </xs:group>

    <xs:attributeGroup name="AtributosPersonal">
        <xs:attribute name="fecha" type="xs:date" use="required" />
        <xs:attribute name="multinacional" type="xs:boolean" use="required" />
        <xs:attribute name="moneda" type="xs:string" fixed="Euro" use="required" />
    </xs:attributeGroup>

    <xs:attributeGroup name="AtributosDepartamento">
        <xs:attribute name="codigo" type="xs:ID" use="optional" />
        <xs:attribute name="nombre-departamento" type="tipoDepartamento" use="optional" />
    </xs:attributeGroup>

    <xs:simpleType name="tipoDepartamento">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Administracion" />
            <xs:enumeration value="InformÃ¡tica" />
            <xs:enumeration value="Marketing" />
            <xs:enumeration value="Recursos-humanos" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoClave">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{1}\D{1}[a-z]{2,4}[A-Z]?[KYH]{1}.{0,3}" />
            <xs:length value="8" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoTexto">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
            <xs:maxLength value="40" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== juan022/asix22/m04/uf1/a2/act8/personal.xml
<?xml version="1.0" encoding="UTF-8"?>
<personal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="personal.xsd" fecha="2021-10-20" multinacional="false"
moneda="Euro">
    <datos-generales>
        <nombre-empresa>Navarra 4 Internet</nombre-empresa>
        <numero-trabajadores>6</numero-trabajadores>
        <sector>
            <tecnologia />
        </sector>
    </datos-generales>
    <datos-departamentos>
        <departamento codigo="ADMIN" nombre-departamento="Administracion">
            <jefe>
                <nombre-y-apellidos>Ana Sanz Ruiz</nombre-y-apellidos>
                <salario>4700</salario>
                <clave usuario="anasan">3%abZKi6</clave>
            </jefe>
            <empleado>
                <nombre-y-apellidos>Juan Gil Rus</nombre-y-apellidos>
                <baja />
                <salario>2200</salario>
            </empleado>
            <empleado>
                <nombre-y-apellidos>Lucas Lopez Tapia</nombre-y-apellidos>
                <salario>2215</salario>
            </empleado>
        </departamento>
        <departamento codigo="INFOR" nombre-departamento="Informática">
            <jefe>
                <nombre-y-apellidos>Isabel Gómez Pérez</nombre-y-apellidos>
                <baja />
                <salario>5200</salario>
                <clave usuario="isabelgo">8$abcdHj</clave>
            </jefe>
            <empleado>
                <nombre-y-apellidos>Oscar Lee Blesa</nombre-y-apellidos>
                <salario>3109</salario>
            </empleado>
        </departamento>
        <departamento>
            <jefe>
                <nombre-y-apellidos>Luis Mar Herreros</nombre-y-apellidos>
                <salario>5111</salario>
                <clave>2$x1zY@</clave>
            </jefe>
        </departamento>
    </datos-departamentos>
</personal>
