<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE geografia [
    <!ELEMENT geografia (paises, ciudades)>
    <!ELEMENT paises (pais)*>
    <!ELEMENT pais (#PCDATA)>
    <!ATTLIST pais codpais ID #REQUIRED>
    <!ELEMENT ciudades (ciudad)*>
    <!ELEMENT ciudad (#PCDATA)>
    <!ATTLIST ciudad pais IDREF #IMPLIED>
]>
<geografia>
    <paises>
        <pais codpais="p1">Argentina</pais>
        <pais codpais="p2">Austria</pais>
        <pais codpais="p3">Japón</pais>
        <pais codpais="p4">Noruega</pais>
        <pais codpais="p5">España</pais>
    </paises>
    <ciudades>
        <ciudad pais="p3">Osaka</ciudad>
        <ciudad pais="p4">Oslo</ciudad>
        <ciudad pais="p5">Sevilla</ciudad>
        <ciudad pais="p3">Tokio</ciudad>
        <ciudad pais="p2">Viena</ciudad>
    </ciudades>
</geografia>
<!-- geografia.xml-->