<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pizzas [
    <!ELEMENT pizzas (ingredientes, tipos)>
    <!ELEMENT ingredientes (ingrediente)*>
    <!ELEMENT ingrediente (#PCDATA)>
    <!ATTLIST ingrediente coding ID #REQUIRED>
    <!ELEMENT tipos (tipo)*>
    <!ELEMENT tipo EMPTY>
    <!ATTLIST tipo nombre CDATA #REQUIRED>
    <!ATTLIST tipo ingredientes IDREF #REQUIRED>
]>
<pizzas>
    <ingredientes>
        <ingrediente coding="HUE">Huevo</ingrediente>
        <ingrediente coding="CHA">Champiñón</ingrediente>
        <ingrediente coding="CHO">Chorizo</ingrediente>
        <ingrediente coding="CAL">Calabacín</ingrediente>
        <ingrediente coding="JAM">Jamón de York</ingrediente>
        <ingrediente coding="ZAN">Zanahoria</ingrediente>
    </ingredientes>
    <tipos>
        <tipo nombre="Fantástica" ingredientes="CAL"/>
        <tipo nombre="Fantástica" ingredientes="CHA"/>
        <tipo nombre="Fantástica" ingredientes="ZAN"/>
        <tipo nombre="Sabrosa" ingredientes="CHA"/>
        <tipo nombre="Sabrosa" ingredientes="CHO"/>
        <tipo nombre="Sabrosa" ingredientes="JAM"/>
        <tipo nombre="Sabrosa" ingredientes="HUE"/>
    </tipos>
</pizzas>
<!-- pizzas.xml
    ¿¿revisar??-->