=== juan022/asix22/m04/uf1/examen/pelicules.dtd
<!ELEMENT cartelera (pelicula)*>
 <!ELEMENT pelicula (titulo, titulo_original?, nacionalidad, genero, (clasificacion | sin_clasificar), sinopsis, director, reparto, web?) >
 <!ELEMENT titulo (#PCDATA)>
 <!ELEMENT titulo_original (#PCDATA)>
 <!ELEMENT nacionalidad (#PCDATA)>
 <!ELEMENT genero (#PCDATA)>
 <!ELEMENT clasificacion EMPTY>
 <!ELEMENT sin_clasificar EMPTY>
 <!ELEMENT sinopsis (#PCDATA)>
 <!ELEMENT director (#PCDATA)>
 <!ELEMENT reparto (actor)+>
 <!ELEMENT web (#PCDATA)>
 <!ELEMENT actor (#PCDATA)>

 <!ATTLIST pelicula codigo ID #REQUIRED>
 <!ATTLIST pelicula duracion CDATA "">
 <!ATTLIST pelicula anyo CDATA "2003">
 <!ATTLIST clasificacion edad (8 | 12 | 16 | 18 | tp) #REQUIRED>

=== juan022/asix22/m04/uf1/examen/pelicules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cartelera SYSTEM "pelicules.dtd">
<cartelera>
    <pelicula codigo="A12" duracion="98min" anyo="2003">
        <titulo>Hola</titulo>
        <titulo_original>Hola, mar</titulo_original>
        <nacionalidad>España</nacionalidad>
        <genero>Drama</genero>
        <sin_clasificar />
        <sinopsis>Saludo al mar</sinopsis>
        <director>Jorge</director>
        <reparto>
            <actor>Alicia</actor>
            <actor>Roberto</actor>
        </reparto>
        <web>www.holamar.com</web>
    </pelicula>
    <pelicula codigo="A4" duracion="99min" anyo="2006">
        <titulo>Adio</titulo>
        <nacionalidad>España</nacionalidad>
        <genero>Drama</genero>
        <clasificacion edad="16" />
        <sinopsis>Saludo al mar</sinopsis>
        <director>Jorge</director>
        <reparto>
            <actor>Alicia</actor>
            <actor>Roberto</actor>
        </reparto>
    </pelicula>
</cartelera>
