<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE concessionari [
    <!ELEMENT concessionari (modelos*)>
    <!ELEMENT modelos (modelo*)>
    <!ELEMENT modelo (descripcion?, modelos_relacionados?, motor_relacionado?)>
    <!ATTLIST modelo refe ID #REQUIRED>
    <!ELEMENT descripcion (tipo_motor, potencia, cambio_manual, consumo_medio, precio_base)>
    <!ELEMENT tipo_motor (#PCDATA)>
    <!ELEMENT potencia (#PCDATA)>
    <!ELEMENT cambio_manual EMPTY>
    <!ELEMENT consumo_medio (#PCDATA)>
    <!ELEMENT precio_base (#PCDATA)>
    <!ELEMENT modelos_relacionados EMPTY>
    <!ATTLIST modelos_relacionados relacion IDREFS #IMPLIED>
    <!ELEMENT motor_relacionado EMPTY>
    <!ATTLIST motor_relacionado relacion IDREFS #IMPLIED>
]>
<concessionari>
    <modelos>
        <modelo refe="_556">
        </modelo>
        <modelo refe="_555">
            <descripcion>
                <tipo_motor>1.998cc de cuetro cilindros</tipo_motor>
                <potencia>128CV</potencia>
                <cambio_manual />
                <consumo_medio>11 a los 100km</consumo_medio>
                <precio_base>2.225.000</precio_base>
            </descripcion>
            <modelos_relacionados relacion="_444 _556"></modelos_relacionados>
            <motor_relacionado relacion="_556"></motor_relacionado>
        </modelo>
        <modelo refe="_557">
        </modelo>
        <modelo refe="_154">
        </modelo>
        <modelo refe="_444">
            <descripcion>
                <tipo_motor>2000cc 16v de cuatro cilindors</tipo_motor>
                <potencia>128CV</potencia>
                <cambio_manual />
                <consumo_medio>11 a los 100km</consumo_medio>
                <precio_base>2.500.000</precio_base>
            </descripcion>
            <modelos_relacionados relacion="_555 _154" />
            <motor_relacionado relacion="_556" />
        </modelo>
    </modelos>
</concessionari>